### ISSUE TITLE
Disabling the menu

### ISSUE THREAD

**Issue by Hate9** [gokiburikin/gkbrkn_noita#1]
Is there a way to disable the config menu once I've set up the mod the way I want?

**Comment by gokiburikin** [comment]
There currently isn't an easily accessible way to do it, but commenting out https://github.com/gokiburikin/gkbrkn_noita/blob/c4e3cac589b9f6a3a54e87cf9edae7115010944a/init.lua#L202 should work.

If you have any suggestions about a way to more elegantly handle it in-game I'll see what I can do about it.

**Comment by Hate9** [comment]
I mean, you could have a setting in that menu, so it's disabled next time the mod loads.
Obviously, there'd be no way to re-enable it without reinstalling the mod, but it'd be easier than the current solution.

**Comment by gokiburikin** [comment]
https://github.com/gokiburikin/gkbrkn_noita/commit/46db91b5bea58edd0b20ce1de5de4a6c03ef885b adds an auto-hide option which should be good enough.
