### ISSUE TITLE
Toxic Sludge Immunity

### ISSUE THREAD

**Issue by Ashnal** [gokiburikin/gkbrkn_noita#2]
One thing I noticed, there's a vanilla bug/mechanic where you'll still take damage from various toxic sludge material states even when you have toxic sludge immunity. 

For example, while standing in liquid toxic sludge, if it evaporates into gas you'll be damaged by the gas when you'd expect to be immune. Can you add a tweak to fix this, and ensure all states of toxic sludge do not damage you when toxic sludge immune?

**Comment by gokiburikin** [comment]
As far as the modding community is aware material immunity is not accessible right now. I'll take another look just to confirm, but it's likely that it's not currently possible.

**Comment by gokiburikin** [comment]
I've made a bit of progress and found that material immunity is technically possible with a bit of a workaround. I'll continue to see what I can do on this front, but at least we know it's possible now.

**Comment by Ashnal** [comment]
My best guess is that Toxic Sludge Immunity might make you immune to things with the [Radioactive] tag .... which the toxic sludge gas lacks for some reason. Have you tested adding that tag to the materials that lack it?

**Comment by gokiburikin** [comment]
Okay looks like someone got material immunity working. I'll see what I can do with this information. For now here's their immunity mod. https://modworkshop.net/mydownloads.php?action=view_down&did=26120

**Comment by gokiburikin** [comment]
Nevermind I guess they were mistaken.

**Comment by gokiburikin** [comment]
This has been addressed in the base game.
