### ISSUE TITLE
Can u write a separate localization file？

### ISSUE THREAD

**Issue by 2668643936** [gokiburikin/gkbrkn_noita#3]
？？？

**Comment by gokiburikin** [comment]
I am working on moving to a localization file now.

**Comment by gokiburikin** [comment]
https://github.com/gokiburikin/gkbrkn_noita/commit/edb376c30d3a8726dd05fce6260dc68b91ccc8d3 adds a localization file. A usage example can be found here https://github.com/gokiburikin/gkbrkn_noita/releases/download/c66/gkbrkn_translate-c66.zip
