### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by gralewski** [gokiburikin/gkbrkn_noita#6]
in
mods\quality_of_life_ommel\qol_files\scripts\gun\procedural\wand_level_from_biome.lua
there is
dofile_once("mods/quality_of_life_ommel/**files/qol_new_data**/scripts/biomes/biome_difficulty_maps.lua")
shouldn't it be
dofile_once("mods/quality_of_life_ommel/**qol_files**/scripts/biomes/biome_difficulty_maps.lua")
?

**Comment by gokiburikin** [comment]
quality of life is not my mod, but you're probably right. you're looking for https://modworkshop.net/mydownloads.php?action=view_down&did=25809
