### ISSUE TITLE
hyper casting breaks luminous drill

### ISSUE THREAD

**Issue by MojoMojosoup** [gokiburikin/gkbrkn_noita#7]
the luminous drill spell can't dig when you have the hyper casting perk
![noita-20200202-151417-2128176226-00003831](https://user-images.githubusercontent.com/44834581/73609528-ca6de280-45ce-11ea-9163-6636642e30d2.gif)

**Comment by gokiburikin** [comment]
Fixed by https://github.com/gokiburikin/gkbrkn_noita/commit/ef4586466b6c0c4c97195f0faf3922dd2a937921
